# Checks that our first-party packages that depend on TabPFN work correctly.
name: First Party Compatibility
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: compatibility-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_first_party_packages:
    name: Test ${{ matrix.repo-name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo-name:
          - tabpfn-extensions
          - tabpfn-time-series

    steps:
      - name: Checkout TabPFN at current ref
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          path: TabPFN

      - name: Checkout ${{ matrix.repo-name }}
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: PriorLabs/${{ matrix.repo-name }}
          path: ${{ matrix.repo-name }}

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.13"

      - name: Set up uv
        uses: astral-sh/setup-uv@ed21f2f24f8dd64503750218de024bcf64c7250a # v7.1.5

      - name: Install dependencies and run tests
        env:
          HF_TOKEN: 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 # Token for v2.5 repo
          FAST_TEST_MODE: 1 # Configures -extensions to run a smaller set of tests.
        run: |
          cd ${{ matrix.repo-name }}
          uv run --with ../TabPFN --all-extras pytest -m "not uses_tabpfn_client"
